### ISSUE TITLE
bug in history of get object

### ISSUE THREAD

**Issue by vahidtwo** [unfoldadmin/django-unfold#260]
when i want to open an object history i got error 
```django.template.exceptions.TemplateSyntaxError: 'counter' argument to 'blocktranslate' tag must be a number.```
this is the traceback
```
Traceback (most recent call last):
  File ".......python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File ".......python3.8/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File ".......python3.8/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File ".......python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File ".......python3.8/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File ".......python3.8/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File ".......python3.8/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File ".......python3.8/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File ".......python3.8/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File ".......python3.8/site-packages/django/templatetags/i18n.py", line 141, in render
    raise TemplateSyntaxError(
```
```

**Comment by lukasvinclav** [comment]
I'm not able to reproduce the issue. Would you mind to create a repository with the minimal example?

**Comment by SDeVuyst** [comment]
> I'm not able to reproduce the issue. Would you mind to create a repository with the minimal example?

I have the same issue, if you can check out my[ repo](https://github.com/SDeVuyst/saranalaya-admin/tree/unfold_theme) (check that you're on the unfold_theme branch) that would be amazing :)

Thanks
