### ISSUE TITLE
History raises TemplateSyntaxError

### ISSUE THREAD

**Issue by SDeVuyst** [unfoldadmin/django-unfold#553]
I installed the django simple history app. The history buttons appears, but when clicked it raises a TemplateSyntaxError.:
```
TemplateSyntaxError at /admin/admin_app/child/1/history/
'counter' argument to 'blocktranslate' tag must be a number.
Request Method: | GET
-- | --
http://localhost:8100/admin/admin_app/child/1/history/
3.2.25
TemplateSyntaxError
'counter' argument to 'blocktranslate' tag must be a number.
/usr/local/lib/python3.12/site-packages/django/templatetags/i18n.py, line 141, in render
/usr/local/bin/python
3.12.4
['/code',  '/usr/local/lib/python312.zip',  '/usr/local/lib/python3.12',  '/usr/local/lib/python3.12/lib-dynload',  '/usr/local/lib/python3.12/site-packages']
Tue, 09 Jul 2024 17:04:46 +0200
```

You can check out my repo in which this occurs [here](https://github.com/SDeVuyst/saranalaya-admin/tree/unfold_theme). (Make sure you are on the unfold_theme branch)

If you need more info or anything else, don't hesitate to ask.
Thanks

Traceback:
```
Environment:


Request Method: GET
Request URL: http://localhost:8100/admin/admin_app/child/1/history/

Django Version: 3.2.25
Python Version: 3.12.4
Installed Applications:
['admin_app.apps.AdminAppConfig',
 'unfold',
 'unfold.contrib.filters',
 'unfold.contrib.inlines',
 'unfold.contrib.simple_history',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'simple_history',
 'dbbackup',
 'storages']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware']


Template error:
In template /usr/local/lib/python3.12/site-packages/unfold/templates/unfold/layouts/skeleton.html, error at line 0
   'counter' argument to 'blocktranslate' tag must be a number.
   1 : {% load i18n static unfold %}
   2 : 
   3 : {% get_current_language as LANGUAGE_CODE %}
   4 : {% get_current_language_bidi as LANGUAGE_BIDI %}
   5 : 
   6 : {% capture as branding silent %}{% block branding %}{% endblock %}{% endcapture %}
   7 : {% capture as pretitle silent %}{% block pretitle %}{% endblock %}{% endcapture %}
   8 : {% capture as content_title silent %}{% block content_title %}{% if title %}{{ title }}{% endif %}{% endblock %}{% endcapture %}
   9 : {% capture as content_subtitle silent %}{% block content_subtitle %}{% if subtitle %}{{ subtitle }}{% endif %}{% endblock %}{% endcapture %}
   10 : {% capture as nav_global silent %}{% block nav-global %}{% endblock %}{% endcapture %}


Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.12/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/usr/local/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.12/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.12/site-packages/django/templatetags/i18n.py", line 141, in render
    raise TemplateSyntaxError(

Exception Type: TemplateSyntaxError at /admin/admin_app/child/1/history/
Exception Value: 'counter' argument to 'blocktranslate' tag must be a number.

```

**Comment by lukasvinclav** [comment]
Why you are installing django 3.2? Can you test it on 5.x?
